"""Mindquad Snakemake workflow entry point."""

configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/bids_setup.smk"
include: "rules/mriqc.smk"


rule all:
    """Target rule executing BIDS setup and MRIQC quality control across all subjects."""
    input:
        "bids/dataset_description.json",
        expand("bids/sub-{subject}/.bids_organized", subject=get_bids_subjects()),
        expand(
            "derivatives/mriqc/sub-{subject}/.mriqc_complete",
            subject=get_bids_subjects(),
        ),
        expand(
            "derivatives/mriqc/sub-{subject}.html",
            subject=get_bids_subjects(),
        ),
        "derivatives/mriqc/.mriqc_group_complete",
