"""Mindquad Snakemake workflow entry point."""

configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/bids_setup.smk"
include: "rules/mriqc.smk"
include: "rules/fastsurfer.smk"
include: "rules/fmriprep.smk"
include: "rules/qsiprep.smk"
include: "rules/coregistration.smk"
include: "rules/hcp_postfreesurfer.smk"


rule all:
    """Target rule for BIDS, QC, FastSurfer, fMRIPrep, QSIPrep, Coreg, and HCP."""
    input:
        "bids/dataset_description.json",
        expand(
            "bids/sub-{subject}/.bids_organized",
            subject=get_bids_subjects(),
        ),
        expand(
            "derivatives/mriqc/sub-{subject}/.mriqc_complete",
            subject=get_bids_subjects(),
        ),
        expand(
            "derivatives/mriqc/sub-{subject}.html",
            subject=get_bids_subjects(),
        ),
        "derivatives/mriqc/.mriqc_group_complete",
        expand(
            "derivatives/fastsurfer/sub-{subject}/.fastsurfer_complete",
            subject=get_bids_subjects(),
        ),
        expand(
            "derivatives/fastsurfer/sub-{subject}/"
            "mri/aparc.DKTatlas+aseg.deep.mgz",
            subject=get_bids_subjects(),
        ),
        expand(
            "derivatives/fmriprep/sub-{subject}/.fmriprep_complete",
            subject=get_bids_subjects(),
        ),
        expand(
            "derivatives/fmriprep/sub-{subject}.html",
            subject=get_bids_subjects(),
        ),
        expand(
            "derivatives/qsiprep/sub-{subject}/.qsiprep_complete",
            subject=get_bids_subjects(),
        ),
        expand(
            "derivatives/qsiprep/sub-{subject}.html",
            subject=get_bids_subjects(),
        ),
        expand(
            "derivatives/coregistration/sub-{subject}/"
            ".coregistration_complete",
            subject=get_bids_subjects(),
        ),
        expand(
            "derivatives/coregistration/sub-{subject}/"
            "anat/sub-{subject}_space-T1w_desc-coreg_T2w.nii.gz",
            subject=get_bids_subjects(),
        ),
        expand(
            "derivatives/coregistration/sub-{subject}.html",
            subject=get_bids_subjects(),
        ),
        expand(
            "derivatives/hcp/sub-{subject}/.hcp_complete",
            subject=get_bids_subjects(),
        ),
        expand(
            "derivatives/hcp/sub-{subject}/MNINonLinear/fsaverage_LR32k/"
            "sub-{subject}.32k_fs_LR.wb.spec",
            subject=get_bids_subjects(),
        ),


