"""Mindquad Snakemake workflow entry point."""

import os

default_config = os.path.join(workflow.basedir, "../config/config.yaml")
if os.path.exists(default_config):
    configfile: default_config

include: "rules/common.smk"
include: "rules/bids_setup.smk"
include: "rules/mriqc.smk"
include: "rules/fastsurfer.smk"
include: "rules/fmriprep.smk"
include: "rules/qsiprep.smk"
include: "rules/coregistration.smk"
include: "rules/hcp_postfreesurfer.smk"
include: "rules/mrs.smk"


rule all:
    """Target rule for BIDS, QC, FastSurfer, fMRIPrep, QSIPrep, Coreg, HCP, and MRS."""
    input:
        f"{get_bids_dir()}/dataset_description.json",
        expand(
            f"{get_bids_dir()}/sub-{{subject}}/.bids_organized",
            subject=get_bids_subjects(),
        ),
        expand(
            f"{get_mriqc_dir()}/sub-{{subject}}/.mriqc_complete",
            subject=get_bids_subjects(),
        ),
        expand(
            f"{get_mriqc_dir()}/sub-{{subject}}.html",
            subject=get_bids_subjects(),
        ),
        f"{get_mriqc_dir()}/.mriqc_group_complete",
        expand(
            f"{get_fastsurfer_dir()}/sub-{{subject}}/.fastsurfer_complete",
            subject=get_bids_subjects(),
        ),
        expand(
            f"{get_fastsurfer_dir()}/sub-{{subject}}/mri/aparc.DKTatlas+aseg.deep.mgz",
            subject=get_bids_subjects(),
        ),
        expand(
            f"{get_fmriprep_dir()}/sub-{{subject}}/.fmriprep_complete",
            subject=get_bids_subjects(),
        ),
        expand(
            f"{get_fmriprep_dir()}/sub-{{subject}}.html",
            subject=get_bids_subjects(),
        ),
        expand(
            f"{get_qsiprep_dir()}/sub-{{subject}}/.qsiprep_complete",
            subject=get_bids_subjects(),
        ),
        expand(
            f"{get_qsiprep_dir()}/sub-{{subject}}.html",
            subject=get_bids_subjects(),
        ),
        expand(
            f"{get_coregistration_dir()}/sub-{{subject}}/.coregistration_complete",
            subject=get_bids_subjects(),
        ),
        expand(
            f"{get_coregistration_dir()}/sub-{{subject}}/anat/sub-{{subject}}_space-T1w_desc-coreg_T2w.nii.gz",
            subject=get_bids_subjects(),
        ),
        expand(
            f"{get_coregistration_dir()}/sub-{{subject}}.html",
            subject=get_bids_subjects(),
        ),
        expand(
            f"{get_hcp_dir()}/sub-{{subject}}/.hcp_complete",
            subject=get_bids_subjects(),
        ),
        expand(
            f"{get_hcp_dir()}/sub-{{subject}}/MNINonLinear/fsaverage_LR32k/sub-{{subject}}.32k_fs_LR.wb.spec",
            subject=get_bids_subjects(),
        ),
        expand(
            f"{get_mrs_dir()}/sub-{{subject}}/.mrs_complete",
            subject=get_bids_subjects(),
        ),
        expand(
            f"{get_mrs_dir()}/sub-{{subject}}.html",
            subject=get_bids_subjects(),
        ),
        expand(
            f"{get_mrs_dir()}/sub-{{subject}}/quantities.csv",
            subject=get_bids_subjects(),
        ),
